INSERT INTO Property VALUES('5225 dundas rd','Red Hill');
INSERT INTO Property VALUES('8037 main st','Orchard');
INSERT INTO Property VALUES('7247 maple ave','Little Bighorn');
INSERT INTO Property VALUES('5477 queen st','Red Hill');
INSERT INTO Property VALUES('6431 cedar st','Le Plateau');
INSERT INTO Property VALUES('2029 vimy st','Little Bighorn');
INSERT INTO Property VALUES('3925 pine rd','Little Bighorn');
INSERT INTO Property VALUES('7679 alfred st','Red Hill');
INSERT INTO Property VALUES('3707 queen st','Le Plateau');
INSERT INTO Property VALUES('4258 bay ave','Le Plateau');
INSERT INTO Property VALUES('3116 simcoe st','Castle Hill');
INSERT INTO Property VALUES('8309 regent ave','Castle Hill');
INSERT INTO Property VALUES('592 frederick ave','Toa Payoh');
INSERT INTO Property VALUES('927 20th ave','Little Bighorn');
INSERT INTO Property VALUES('9897 stanley way','Little Bighorn');
INSERT INTO Property VALUES('5888 queen st','Little Bighorn');
INSERT INTO Property VALUES('4789 elgin st','Toa Payoh');
INSERT INTO Property VALUES('5310 concession road 6','Toa Payoh');
INSERT INTO Property VALUES('3234 peel st','Le Plateau');
INSERT INTO Property VALUES('7596 alfred st','Toa Payoh');
INSERT INTO Property VALUES('126 st. catherine st','Orchard');
INSERT INTO Property VALUES('3048 simcoe st','Chinatown');
INSERT INTO Property VALUES('986 cedar st','Orchard');
INSERT INTO Property VALUES('4104 college ave','Chinatown');
INSERT INTO Property VALUES('4103 frederick ave','Chinatown');
INSERT INTO Property VALUES('5388 wellington st','Chinatown');
INSERT INTO Property VALUES('8898 coastal highway','Toa Payoh');
INSERT INTO Property VALUES('273 elgin st','Red Hill');
INSERT INTO Property VALUES('7981 alfred st','Little Bighorn');
INSERT INTO Property VALUES('1837 regent ave','Toa Payoh');
INSERT INTO Property VALUES('5754 disputed rd','Orchard');
INSERT INTO Property VALUES('6311 argyle st','Toa Payoh');
INSERT INTO Property VALUES('9485 dundas rd','Castle Hill');
INSERT INTO Property VALUES('2373 concession road 6','Red Hill');
INSERT INTO Property VALUES('4008 balmoral st','Orchard');
INSERT INTO Property VALUES('3251 20th ave','Orchard');
INSERT INTO Property VALUES('7698 cedar st','Little Bighorn');
INSERT INTO Property VALUES('1192 frederick ave','Castle Hill');
INSERT INTO Property VALUES('9137 pine rd','Castle Hill');
INSERT INTO Property VALUES('2098 lake of bays road','Chinatown');
INSERT INTO Property VALUES('6221 alfred st','Le Plateau');
INSERT INTO Property VALUES('4991 bay ave','Red Hill');
INSERT INTO Property VALUES('5914 king st','Chinatown');
INSERT INTO Property VALUES('4488 park rd','Toa Payoh');
INSERT INTO Property VALUES('3386 lakeview ave','Red Hill');
INSERT INTO Property VALUES('9513 duke st','Orchard');
INSERT INTO Property VALUES('1392 regent ave','Toa Payoh');
INSERT INTO Property VALUES('1997 wellington st','Castle Hill');
INSERT INTO Property VALUES('9138 9th st','Red Hill');
INSERT INTO Property VALUES('5450 st. lawrence ave','Chinatown');
